In [1]:
import tensorflow as tf
import numpy as np

##### What are tensors?

> Tensors are mutlti dimentional arrays with uniform data types.

> 





In [10]:
#create tensor
print("Example of rank 0 tensor : \n")
tensor_rank_0=tf.constant(4)
print(f" Tensor dimension: {tensor_rank_0.ndim} \n Tensor shape :{tensor_rank_0.shape} \n Size of tensor : {tf.size(tensor_rank_0)} \n")

print("Example of rank 1 tensor : \n")
tensor_rank_1=tf.constant([1,2,3])
print(f" Tensor dimension: {tensor_rank_1.ndim} \n Tensor shape :{tensor_rank_1.shape} \n Size of tensor : {tf.size(tensor_rank_1)} \n")

print("Example of rank 2 tensor : \n")
tensor_rank_2=tf.constant([[1],[2],[3]])
print(f" Tensor dimension: {tensor_rank_2.ndim} \n Tensor shape :{tensor_rank_2.shape} \n Size of tensor : {tf.size(tensor_rank_2)} \n")

print("Example of rank 3 tensor : \n")
tensor_rank_3=tf.constant([[[1,3,4],[2,4,7],[3,0,0]]])
print(f" Tensor dimension: {tensor_rank_3.ndim} \n Tensor shape :{tensor_rank_3.shape} \n Size of tensor : {tf.size(tensor_rank_3)} \n")

Example of rank 0 tensor : 

 Tensor dimension: 0 
 Tensor shape :() 
 Size of tensor : 1 

Example of rank 1 tensor : 

 Tensor dimension: 1 
 Tensor shape :(3,) 
 Size of tensor : 3 

Example of rank 2 tensor : 

 Tensor dimension: 2 
 Tensor shape :(3, 1) 
 Size of tensor : 3 

Example of rank 3 tensor : 

 Tensor dimension: 3 
 Tensor shape :(1, 3, 3) 
 Size of tensor : 9 



##### Convert tensor to numpy array
> Method 1: Using np.array(tensor)

> Method 2: Use .numpy()











In [14]:
print("Converting tensor to numpy array :",type(tensor_rank_3))
np_array=np.array(tensor_rank_3)
print(f"type of array: {type(np_array)}")

Converting tensor to numpy array : <class 'tensorflow.python.framework.ops.EagerTensor'>
type of array: <class 'numpy.ndarray'>


In [15]:
print("Converting tensor to numpy array :",type(tensor_rank_3))
np_array=tensor_rank_3.numpy()
print(f"type of array: {type(np_array)}")

Converting tensor to numpy array : <class 'tensorflow.python.framework.ops.EagerTensor'>
type of array: <class 'numpy.ndarray'>


##### What are Ragged Tensors?

* A tensor with variable numbers of elements along some axis is called "ragged". Use `tf.ragged.RaggedTensor` for ragged data.

* String tensors



In [20]:
ragged_list=[[1,2,3,4],[4,5,6],[0]]
ragged_tensor=tf.ragged.constant(ragged_list)
print(f"Shape of ragged tensor: {ragged_tensor.shape} \n Type of ragged tensor :{type(ragged_tensor)}")

Shape of ragged tensor: (3, None) 
 Type of ragged tensor :<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>


In [22]:
string_list=["My name is Prajakta","What is your name?","How are you"]
string_tensor=tf.ragged.constant(string_list)
print(f"Shape of string ragged tensor : {string_tensor.shape} \n Type of ragged tensor :{type(string_tensor)}")

Shape of string ragged tensor : (3,) 
 Type of ragged tensor :<class 'tensorflow.python.framework.ops.EagerTensor'>


##### What are sparse tensors? `tf.sparse.SparseTensor`

Sometimes, your data is sparse, like a very wide embedding space.
TensorFlow supports tf.sparse.SparseTensor and related operations to store sparse data efficiently.

In [23]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


##### Automatic Differentiation and Gradients


Automatic differentiation is useful for implementing machine learning algorithms such as backpropagation.
https://www.tensorflow.org/guide/autodiff]

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

* Computing gradients:
To diffeentiate automatically tensorflow needs to remember what operations happen in what order during the forward pass.
Then during backword pass , Tensorflow traverses this list of operations in reverse order to compute gradient. 

* TensorFlow provides the `tf.GradientTape` API for automatic differentiation; that is, computing the gradient of a computation with respect to some inputs, usually tf.Variables. TensorFlow "records" relevant operations executed inside the context of a tf.GradientTape onto a "tape". TensorFlow then uses that tape to compute the gradients of a "recorded" computation using reverse mode differentiation.

In [5]:
x=tf.Variable([5.0])

with tf.GradientTape() as tape:
  y=x**2

dy_dx=tape.gradient(y,x)
dy_dx.numpy()


array([10.], dtype=float32)

* Let's see how gradients will get calculated

In [28]:
tf.random.set_seed(42)
w= tf.Variable(tf.random.normal((3,2),seed=42,dtype=tf.float32,name="w"))
b=tf.Variable(tf.zeros(2,dtype=tf.float32,name="b"))

x=tf.Variable([[1.,2.,3.]])


with tf.GradientTape() as tape:
  y=x @ w+b
  print(y)
  loss=tf.reduce_mean(y**2)
  print("loss :",loss)


tf.Tensor([[ 2.811394  -0.8994003]], shape=(1, 2), dtype=float32)
loss : tf.Tensor(4.356428, shape=(), dtype=float32)


In [29]:
dl_dw,dl_db=tape.gradient(loss,[w,b])

In [30]:
dl_db,dl_dw

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2.811394 , -0.8994003], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.811394 , -0.8994003],
        [ 5.622788 , -1.7988006],
        [ 8.434182 , -2.698201 ]], dtype=float32)>)

In [31]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[1., 2., 3.]])

with tf.GradientTape() as tape:
  # Forward pass
  y = layer(x)
  loss = tf.reduce_mean(y**2)

# Calculate gradients with respect to every trainable variable
grad = tape.gradient(loss, layer.trainable_variables)

In [32]:
for var, g in zip(layer.trainable_variables, grad):
  print(f'{var.name}, shape: {g.shape}')

dense/kernel:0, shape: (3, 2)
dense/bias:0, shape: (2,)


* Following code fails to calculate a gradient because the tf.Tensor is not "watched" by default, and the tf.Variable is not trainable

In [33]:
# A trainable variable
x0 = tf.Variable(3.0, name='x0')
# Not trainable
x1 = tf.Variable(3.0, name='x1', trainable=False)
# Not a Variable: A variable + tensor returns a tensor.
x2 = tf.Variable(2.0, name='x2') + 1.0
# Not a variable
x3 = tf.constant(3.0, name='x3')

with tf.GradientTape() as tape:
  y = (x0**2) + (x1**2) + (x2**2)

grad = tape.gradient(y, [x0, x1, x2, x3])

for g in grad:
  print(g)

tf.Tensor(6.0, shape=(), dtype=float32)
None
None
None


In [34]:
#you casee list of watched variables
[var.name for var in tape.watched_variables()]

['x0:0']

* **Note** 

To record gradients with respect to a tf.Tensor, call GradientTape.watch(x)

By default, the resources held by a GradientTape are released as soon as the GradientTape.gradient method is called. To compute multiple gradients over the same computation, create a gradient tape with persistent=True. This allows multiple calls to the gradient method as resources are released when the tape object is garbage collected


In [35]:
x = tf.constant([1, 3.0])
with tf.GradientTape(persistent=True) as tape:
  tape.watch(x)
  y = x * x
  z = y * y

print(tape.gradient(z, x).numpy())  # 108.0 (4 * x**3 at x = 3)
print(tape.gradient(y, x).numpy())  # 6.0 (2 * x)

[  4. 108.]
[2. 6.]


* The gradient of multiple targets, the result for each source is: The gradient of the sum of the targets, or equivalently

In [39]:
x=tf.Variable(3.)

with tf.GradientTape() as tape:
  y0=x**2
  y1=1/x

  print(tape.gradient({"y0":y0,"y1":y1},x).numpy() )# derivative of y0 wrt x=> 2*x +derivative of y1 wrt x=>-1/x^2)
  

5.888889


* In some cases it would be convenient to get 0 instead of None for unconnected gradients. You can decide what to return when you have unconnected gradients using the unconnected_gradients argument:

In [41]:
x=tf.Variable([1.,2.,3.])
y=tf.Variable([4.])

with tf.GradientTape() as tape:
  z=y**y

print(tape.gradient(z,x,unconnected_gradients=tf.UnconnectedGradients.ZERO))

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


##### Tensorflow graphs


Graph execution means that tensor computations are executed as a TensorFlow graph, sometimes referred to as a tf.Graph or simply a "graph."

`Graphs are data structures that contain a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations. `


We can use your TensorFlow graph in environments that don't have a Python interpreter, like mobile applications, embedded devices, and backend servers.


You create and run a graph in TensorFlow by using `tf.function`

In [64]:
# define python function
def regular_function(x1,w1,b):
  y=tf.matmul(x1,w1)
  y=y+b
  return y


#create variables
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

In [66]:
orig_value=regular_function(x1,y1,b1)
orig_value

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

In [72]:
a_function_that_uses_a_graph = tf.function(regular_function)

In [73]:
tf_function_value =a_function_that_uses_a_graph(x1,y1,b1).numpy()
tf_function_value

array([[12.]], dtype=float32)

In [74]:
orig_value==tf_function_value

<tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[ True]])>

* If we want to run Graph executio function with eager execution use `tf.config.run_functions_eagerly(True)`

In [75]:
@tf.function
def get_MSE(y_true, y_pred):
  print("Calculating MSE!")
  sq_diff = tf.pow(y_true - y_pred, 2)
  return tf.reduce_mean(sq_diff)

In [78]:
y_true = tf.random.uniform([5], maxval=10, dtype=tf.int32)
y_pred = tf.random.uniform([5], maxval=10, dtype=tf.int32)
error = get_MSE(y_true, y_pred)
error = get_MSE(y_true, y_pred)
error = get_MSE(y_true, y_pred)

"""To explain, the print statement is executed when Function runs the original code in order to create the graph in a process known as
 "tracing". Tracing captures the TensorFlow operations into a graph, and print is not captured in the graph.
 That graph is then executed for all three calls without ever running the Python code again."""

'To explain, the print statement is executed when Function runs the original code in order to create the graph in a process known as\n "tracing". Tracing captures the TensorFlow operations into a graph, and print is not captured in the graph.\n That graph is then executed for all three calls without ever running the Python code again.'

In [80]:
y_true = tf.random.uniform([5], maxval=10, dtype=tf.int64)
y_pred = tf.random.uniform([5], maxval=10, dtype=tf.int64)
error = get_MSE(y_true, y_pred)
error = get_MSE(y_true, y_pred)
error = get_MSE(y_true, y_pred)

Calculating MSE!


* tf.function is commonly used to speed up training loops,

##### Tensor slicing

In [3]:
import tensorflow as tf
import numpy as np

In [5]:
t1=tf.constant([0,1,2,3,4,5,6,7,8,9])
tf.slice(t1,begin=[0],size=[3],name="slice1")

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [7]:
t1[0:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [8]:
t1[-3:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9], dtype=int32)>

In [9]:
t2=tf.constant([[1,2,3],[4,5,6],[7,8,9],[1,5,0]])
t2.shape

TensorShape([4, 3])

In [11]:
t2[:-1,1:3]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 9]], dtype=int32)>

In [12]:
t2.ndim

2

In [13]:
t3=tf.constant([[[1,2,3],[5,6,7]],
                [[4,4,5],[9,9,0]]])
t3

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[4, 4, 5],
        [9, 9, 0]]], dtype=int32)>

In [15]:
tf.slice(t3,
         begin=[1,1,0],
         size=[1,1,3])

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[9, 9, 0]]], dtype=int32)>

In [16]:
alphabet = tf.constant(list('abcdefghijklmnopqrstuvwxyz'))

print(tf.gather(alphabet,
                indices=[2, 0, 19, 18]))

tf.Tensor([b'c' b'a' b't' b's'], shape=(4,), dtype=string)
