**Tensorflow Fundamentals**



In [ ]:
#Import tensorflow
import tensorflow as tf

In [ ]:
print(tf.__version__)#check tensorflow version

2.4.1


In [ ]:
#create tensor with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions
scalar.ndim #ndim is number of dimensions

0

In [ ]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[10,4,5],
                   [5,6,0]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  4,  5],
       [ 5,  6,  0]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_mtx=tf.constant([[3.,4.,6.],[3,4,5],[6.,9.,3.]],dtype=tf.float16)
another_mtx

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[3., 4., 6.],
       [3., 4., 5.],
       [6., 9., 3.]], dtype=float16)>

In [ ]:
another_mtx.ndim

2

In [ ]:
tensor =tf.constant([
                     [[1,2],[7,8]],
                     [[3,4],[6,7]],
                     [[6,9],[0,2]]
],dtype=tf.float16)

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float16, numpy=
array([[[1., 2.],
        [7., 8.]],

       [[3., 4.],
        [6., 7.]],

       [[6., 9.],
        [0., 2.]]], dtype=float16)>

In [ ]:
tensor.ndim

3

**scalar**: single number

**vector** : number with direction

**matrix**: 2-dimensional array of numbers

**tensor**: n-dimensional array of numbers


In [ ]:
changeable_tensor=tf.Variable([10,7])
constant_tensor=tf.constant([11,2])

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
constant_tensor[0].assign(7) # cannot modify constant tensors
constant_tensor

AttributeError: ignored

**Creating random tensors**

In [ ]:
random_l=tf.random.Generator.from_seed(42) # set seed for reproduciability
random_l=random_l.normal(shape=(3,2))#picks random values from normal distribution
random_l

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_l==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>


`tf.random.shuffle(value, seed=None, name=None)`

The tensor is shuffled along dimension 0, such that each value[j] is mapped to one and only one output[i]


Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

**Its interactions with operation-level seeds is as follows:**

If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. 

If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.

If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.


If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
test1_shuffle=tf.random.Generator.from_seed(42)
test1_shuffle=test1_shuffle.normal(shape=(3,2))
tf.random.shuffle(test1_shuffle) #this will not generate constant result

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(42) #global level seed
test1_shuffle=tf.random.Generator.from_seed(42) #operation level seed
test1_shuffle=test1_shuffle.normal(shape=(3,2))
tf.random.shuffle(test1_shuffle) #this will  generate constant result

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

**Different ways to create tensors**

In [ ]:
tf.ones(shape=(2,2),dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 1],
       [1, 1]], dtype=int16)>

In [ ]:
tf.zeros(shape=(2,2),dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

**Turn numpy arrays into tensors:**

numpy arrays and tensors are very similar but tensor can run on GPU much faster that numy array(computation willl be faster)

In [ ]:
import numpy as np

In [ ]:
numpy_A=np.arange(1,25,dtype=np.int8)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int8)

In [ ]:
#convert above numpy array to tensor

tensor_np=tf.constant(numpy_A)
tensor_np

<tf.Tensor: shape=(24,), dtype=int8, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int8)>

Getting information from tensors

In [ ]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
#get first 2 elements from each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#create tensor of rank 2

rank_2_tensor=tf.constant([[10,7],[2,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
rank_3_tensor=tf.constant([[[10,7],[2,5]],[[10,7],[2,5]],[[10,7],[2,5]]])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  5]],

       [[10,  7],
        [ 2,  5]],

       [[10,  7],
        [ 2,  5]]], dtype=int32)>

In [ ]:
rank_3_tensor.ndim

3

In [ ]:
rank_3_tensor.shape
rank_3_tensor[:,:,-1]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 5],
       [7, 5],
       [7, 5]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
rank_2_tensor[...,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 2,  5]]], dtype=int32)>

**Manipulating tensors**

Basic operations

`+`,`-`,`*`,`/`

In [ ]:
tensor_op1=tf.constant([[10,7],[3,4]])
print(tensor_op1+10)
print(tensor_op1)#reamins unchanged

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_op1*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor_op1-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor_op1/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
#use built in functions

tf.multiply(tensor_op1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(tensor_op1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.subtract(tensor_op1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.divide(tensor_op1,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

**Matrix multiplication**

tensor * tensor => element wise multiplication

tf.matmul(tensor,tensor) => dot product

tensor @ tensor => dot product (here @ is python operator)

In [ ]:
tensor_op1*tensor_op1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
tf.matmul(tensor_op1,tensor_op1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor_op1 @ tensor_op1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#create tensor of (3,2)

tensor_op2=tf.constant([[3,2],[6,7],[2,0]])
print(tensor_op2.shape)

tensor_op3=tf.constant([[3,2,0],[6,7,2]])
print(tensor_op3.shape)

(3, 2)
(2, 3)


In [ ]:
tf.linalg.matmul(tensor_op2,tensor_op3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 20,  4],
       [60, 61, 14],
       [ 6,  4,  0]], dtype=int32)>

In [ ]:

tensor_op4=tf.constant([[3,2],[6,7],[2,0]])
print(tensor_op4.shape)

tensor_op5=tf.constant([[3,2,0],[6,7,2],[1,2,3]])
print(tensor_op5.shape)

(3, 2)
(3, 3)


In [ ]:
#tensor_op4 @ tensor_op5 =>InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,3] [Op:MatMul]

In [ ]:
tf.matmul(tensor_op5,tensor_op5)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 20,  4],
       [62, 65, 20],
       [18, 22, 13]], dtype=int32)>

In [ ]:
print(tensor_op5)

tf.transpose(tensor_op5)

tf.Tensor(
[[3 2 0]
 [6 7 2]
 [1 2 3]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [2, 7, 2],
       [0, 2, 3]], dtype=int32)>

**Tensordot** (also known as tensor contraction) sums the product of elements from a and b over the indices specified by a_axes and b_axes. 

In [ ]:
tf.tensordot(tensor_op5,tf.transpose(tensor_op5),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 32,  7],
       [32, 89, 26],
       [ 7, 26, 14]], dtype=int32)>

In [ ]:
#lets create another rank 2 tensor and perform tensor dot

ten1=tf.constant([[10,7],[3,5]])
ten2=tf.constant([[3,4],[10,20]])

print(tf.tensordot(ten1,ten2,axes=1))

print(tf.matmul(ten1,ten2))


tf.Tensor(
[[100 180]
 [ 59 112]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 180]
 [ 59 112]], shape=(2, 2), dtype=int32)


In [ ]:
print(ten1,ten1.shape)
print(tf.reshape(ten1,shape=(4,1)))

tf.Tensor(
[[10  7]
 [ 3  5]], shape=(2, 2), dtype=int32) (2, 2)
tf.Tensor(
[[10]
 [ 7]
 [ 3]
 [ 5]], shape=(4, 1), dtype=int32)


**Difference beetween transpose and reshape **

In [ ]:
#lets create rank 3 tensor (ndim=3)
ten3=tf.constant([
                   [[1,2],[4,8]],
                   [[9,6],[4,4]],
                   [[3,3],[1,0]]
])
ten3.shape ,ten3.ndim

(TensorShape([3, 2, 2]), 3)

In [ ]:
import numpy as np
arr=np.array([
                   [[1,2],
                    [4,8]],
                   [[9,6],
                    [4,4]],
                   [[3,3],
                    [1,0]]
])
arr.shape

(3, 2, 2)

In [ ]:
print("Noraml tensor :\n",ten3)

print("Transposed tensor : \n",tf.transpose(ten3))

print("Reshape tensor : \n",tf.reshape(ten3,shape=(2,2,3)))

Noraml tensor :
 tf.Tensor(
[[[1 2]
  [4 8]]

 [[9 6]
  [4 4]]

 [[3 3]
  [1 0]]], shape=(3, 2, 2), dtype=int32)
Transposed tensor : 
 tf.Tensor(
[[[1 9 3]
  [4 4 1]]

 [[2 6 3]
  [8 4 0]]], shape=(2, 2, 3), dtype=int32)
Reshape tensor : 
 tf.Tensor(
[[[1 2 4]
  [8 9 6]]

 [[4 4 3]
  [3 1 0]]], shape=(2, 2, 3), dtype=int32)


**Type conversions**

Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory. By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy. This guide describes how to use the Keras mixed precision API to speed up your models. Using this API can improve performance by more than 3 times on modern GPUs and 60% on TPUs.

Today, most models use the float32 dtype, which takes 32 bits of memory. However, there are two lower-precision dtypes, float16 and bfloat16, each which take 16 bits of memory instead. Modern accelerators can run operations faster in the 16-bit dtypes, as they have specialized hardware to run 16-bit computations and 16-bit dtypes can be read from memory faster.

NVIDIA GPUs can run operations in float16 faster than in float32, and TPUs can run operations in bfloat16 faster than float32. Therefore, these lower-precision dtypes should be used whenever possible on those devices. However, variables and a few computations should still be in float32 for numeric reasons so that the model trains to the same quality. The Keras mixed precision API allows you to use a mix of either float16 or bfloat16 with float32, to get the performance benefits from float16/bfloat16 and the numeric stability benefits from float32.


*Note: In this guide, the term "numeric stability" refers to how a model's quality is affected by the use of a lower-precision dtype instead of a higher precision dtype. We say an operation is "numerically unstable" in float16 or bfloat16 if running it in one of those dtypes causes the model to have worse evaluation accuracy or other metrics compared to running the operation in float32.*

All Cloud TPUs support bfloat16.
You should use mixed precision if you use TPUs or NVIDIA GPUs with at least compute capability 7.0, as it will improve performance by up to 3x.

If your model ends in softmax, make sure it is float32. And regardless of what your model ends in, make sure the output is float32

Double the training batch size if it does not reduce evaluation accuracy

On GPUs, ensure most tensor dimensions are a multiple of 8 to maximize performance


Most official models, such as ResNet and Transformer will run using mixed precision by passing --dtype=fp16.

In [ ]:
A=tf.constant([[1.7,5.6]])
A,A.dtype

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.7, 5.6]], dtype=float32)>,
 tf.float32)

In [ ]:
B=tf.cast(A,dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1.7, 5.6]], dtype=float16)>,
 tf.float16)

In [ ]:
#nvidia-smi -L

**Aggregating Tensors**

condensing tensors from multiple values down to a smaller amount of values

In [ ]:
A1=tf.constant([[-9,-4,-0]])
A1

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[-9, -4,  0]], dtype=int32)>

In [ ]:
print(tf.abs(A1).numpy()) #gives absolute values

[[9 4 0]]


* Get minimumn
* Get maximum
* Get mean of tensor
* Get sum of tensor

In [ ]:
#create random tensor with values between 0 and 100 of size 50
tf.random.set_seed(42)
A2=tf.random.Generator.from_seed(42)
A2=A2.normal(shape=(1,50))
A2

<tf.Tensor: shape=(1, 50), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284,
         0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ,
         1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085,
        -0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006,
        -0.52447474, -1.0345329 ,  1.3066901 , -1.5184573 , -0.4585211 ,
         0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 , -1.2659091 ,
        -0.47450137,  2.006022  ,  0.28288034, -0.30288252, -1.443651  ,
         1.0034493 ,  0.20857747,  0.35700995,  1.0648885 ,  1.2432485 ,
        -2.2173238 ,  0.18706243,  0.6617961 ,  0.01380118, -0.24827152]],
      dtype=float32)>

In [ ]:
A2.shape,A2.ndim,tf.size(A2)

(TensorShape([1, 50]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [ ]:
#find minimum of tensor
tf.reduce_min(A2)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.3410842>

In [ ]:
#find maximum
tf.reduce_max(A2)

<tf.Tensor: shape=(), dtype=float32, numpy=2.006022>

In [ ]:
#find mean
tf.reduce_mean(A2)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.20104325>

In [ ]:
#FInd sum
tf.reduce_sum(A2)

<tf.Tensor: shape=(), dtype=float32, numpy=-10.052162>

In [ ]:
import tensorflow_probability as tpf

In [ ]:
#find variance and std dev
tpf.stats.variance(A2)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [ ]:
tpf.stats.stddev(A2)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [ ]:
#create tensor to find maximum positional index
tf.random.set_seed(42)
C=tf.random.uniform(shape=([50]))
C

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
C[tf.argmax(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
C[tf.argmax(C)]==tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
C[tf.argmin(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**Squeezing a tensor**

In [ ]:
#create tensor
tf.random.set_seed(42)
D=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
D

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
D.ndim

5

In [ ]:
D_squeezed=tf.squeeze(D)
D_squeezed,D_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

**one hot encoding**

In [ ]:
some_list=[0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

**Squere   Squere root   log**

In [ ]:
H=tf.range(1,10)
H


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#tf.math.sqrt(H) #type error/Invalid argument error this method accepts float /complex values

In [ ]:
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Tensor and Numpy**

In [ ]:
import numpy as np

In [ ]:
J=tf.constant(np.array([1.,2.,56.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  2., 56.])>

In [ ]:
np.array(J),type(np.array(J))

(array([ 1.,  2., 56.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 1.,  2., 56.]), numpy.ndarray)

In [ ]:
numpy_J=tf.constant(np.array([1,2,3]))
tf_J=tf.constant([1,2,3])

print(type(numpy_J))
print(type(tf_J))


print(numpy_J.dtype)
print(tf_J.dtype)


<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int64'>
<dtype: 'int32'>


References:

https://www.youtube.com/watch?v=tpCFfeUEGs8

https://www.tensorflow.org/
